kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      containers:
       - name: app
         image: faizreza/myappimage01
        # image: faizreza/myappimage02:latest # same as above
        # https://hub.docker.com/repository/docker/faizreza/myappimage02/general : dockerhub reference
        ports:
          - containerPort: 8080  # Tomcat runs on 8080
         # Add health checks
         livenessProbe:
           httpGet:
             path: /addressbook/  # Your app path
             port: 8080
           initialDelaySeconds: 90  # Tomcat takes time to start
           periodSeconds: 10
         readinessProbe:
           httpGet:
             path: /addressbook/
             port: 8080
           initialDelaySeconds: 60
           periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
   name: kubeserve-svc
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector: 
    app: kubeserve
