apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      labels:
        app: kubeserve
    spec:
      containers:
      - name: app
        image: faizreza/myappimage01
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubeserve-svc
spec:
  type: NodePort
  selector:
    app: kubeserve
  ports:
  - port: 80
    targetPort: 8080
